[package]
name = "conventional-commit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["cargo", "wrap_help"] }
fzf-wrapped = "0.1.4"
git-wrapper = "0.6.1"
strum = { version = "0.27.1", features = ["derive"] }
subprocess = "0.2.9"
